

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jmp33?serverTimezone=Asia/Shanghai
    username: devServer
    password: devServer


  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: documents

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka/

server:
  port: 8081
